name: Request to Airflow PROD
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed
jobs:
  request-to-airflow-prod:
    name: Request to Airflow PROD
    runs-on: ubuntu-latest
    steps:
      - name: Request to Airflow PROD C3S-PAN
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://jsonplaceholder.typicode.com/posts'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"title": "pdd", "body": "work", "user-id": 1}'
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
