name: Request to Airflow PROD
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed
jobs:
  request-to-airflow-prod:
    name: Request to Airflow PROD
    runs-on: self-hosted
    steps:
      - name: Request to Airflow PROD C3S-PAN
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://airflow-webserver.pdd-airflow-dev.svc.ar2.io.navercorp.com/api/v1/dags'
          method: 'GET'
          username: ${{ secrets.AIRFLOW_USER }}
          password: ${{ secrets.AIRFLOW_PASSWORD }}
          customHeaders: '{"Content-Type": "application/json"}'
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
